export class MhahConstant {
  Ritu = {
    name: [ 'वसन्त', 'ग्रीष्म', 'वर्षा', 'शरद्', 'हेमन्त', 'शित्'],
    name_en_UK: [
      'Spring',
      'Summer',
      'Monsoon',
      'Autumn',
      'Pre-Winter',
      'Winter',
    ],
  };
  Masa = {
    name:[ 'बैशाख', 'जेठ', 'असार', 'साउन', 'भदौ', 'असोज', 'कार्तिक', 'मंसिर', 'पुष', 'माघ', 'फाल्गुन', 'चैत'],
    name_en_NP: [
      'Baisakha',
      'Jyestha',
      'Asadha',
      'Srabana',
      'Bhadraba',
      'Aswina',
      'Karttika',
      'Margasira',
      'Pausa',
      'Magha',
      'Phalguna',
      'Chaitra',
    ],
  };
  Raasi: {
    name: string[];
    name_en_UK: string[];
  } = {
    name: [ 'मेष', 'वृष', 'मिथुन', 'कर्कट', 'सिंह', 'कन्या', 'तुला', 'वृश्चिक', 'धनु', 'मकर', 'कुम्भ', 'मीन'],
    name_en_UK: [
      'Aries',
      'Taurus',
      'Gemini',
      'Cancer',
      'Leo',
      'Virgo',
      'Libra',
      'Scorpio',
      'Sagittarius',
      'Capricorn',
      'Aquarius',
      'Pisces',
    ],
  };
  Day = {
    name: [ 'आइतबार', 'सोमबार', 'मङ्गलबार', 'बुधबार', 'बिहिबार', 'शुक्रबार', 'शनिबार'],
    name_en_UK: [
      'Sunday',
      'Monday',
      'Tuesday',
      'Wednesday',
      'Thursday',
      'Friday',
      'Saturday',
    ],
  };
  Nakshatra = {
    name: [
      "अश्विनी",
      "भरणी",
      "कृत्तिका",
      "रोहिणी",
      "मृगशीर्ष",
      "आर्द्रा",
      "पुनर्वसु",
      "पुष्य",
      "आश्लेषा",
      "मघा",
      "पूर्व फाल्गुनी",
      "उत्तर फाल्गुनी",
      "हस्त",
      "चित्रा",
      "स्वाति",
      "विशाखा",
      "अनुराधा",
      "ज्येष्ठा",
      "मूल",
      "पूर्व आषाढ",
      "उत्तर आषाढ",
      "श्रवण",
      "धनिष्ठा",
      "शतभिषा",
      "पूर्व भाद्रपदा",
      "उत्तर भाद्रपदा",
      "रेवती"
    ],

    name_en_NP: [
      'Ashwini',
      'Dwija',
      'Krittika',
      'Rohini',
      'Mrigashirsha',
      'Ardra',
      'Punarvasu',
      'Pushya',
      'Ashlesha',
      'Magha',
      'Purva Phalguni',
      'Uttara Phalguni',
      'Hasta',
      'Chitra',
      'Swati',
      'Vishakha',
      'Anuradha',
      'Jyeshtha',
      'Mula',
      'Purva Ashadha',
      'Uttara Ashadha',
      'Sravana',
      'Dhanishta',
      'Shatabhisha',
      'Purva Bhadrapada',
      'Uttara Bhadrapada',
      'Rebati',
    ],
  };
  Paksha = {
    name_en_NP: ['Shukla', 'Krishna'],
    name_en_UK: ['Waxing Moon', 'Waning Moon'],
    name: ['शुक्ल', 'कृष्ण'],
  };

  Tithi = {
    name: [
      "प्रतिपदा",
      "द्वितीया",
      "तृतीया",
      "चतुर्थी",
      "पञ्चमी",
      "षष्ठी",
      "सप्तमी",
      "अष्टमी",
      "नवमी",
      "दशमी",
      "एकादशी",
      "द्वादशी",
      "त्रयोदशी",
      "चतुर्दशी",
      "पूर्णिमा",
      "प्रतिपदा",
      "द्वितीया",
      "तृतीया",
      "चतुर्थी",
      "पञ्चमी",
      "षष्ठी",
      "सप्तमी",
      "अष्टमी",
      "नवमी",
      "दशमी",
      "एकादशी",
      "द्वादशी",
      "त्रयोदशी",
      "चतुर्दशी",
      "अमावास्या"
    ],
    name_en_NP: [
      'Padyami',
      'Vidhiya',
      'Thadiya',
      'Chavithi',
      'Panchami',
      'Shasti',
      'Sapthami',
      'Ashtami',
      'Navami',
      'Dasami',
      'Ekadasi',
      'Dvadasi',
      'Trayodasi',
      'Chaturdasi',
      'Punnami',
      'Padyami',
      'Vidhiya',
      'Thadiya',
      'Chaviti',
      'Panchami',
      'Shasti',
      'Sapthami',
      'Ashtami',
      'Navami',
      'Dasami',
      'Ekadasi',
      'Dvadasi',
      'Trayodasi',
      'Chaturdasi',
      'Amavasya',
    ],
  };
  Karna = {
    name_en_NP: [
      'Bawa',
      'Balava',
      'Kaulava',
      'Taitula',
      'Garaja',
      'Vanija',
      'Vishti',
      'Sakuna',
      'Chatushpada',
      'Nagava',
      'Kimstughana',
    ],
    name:[ 'बव', 'बालव', 'कौलव', 'तैतिल', 'गरज', 'वणिज', 'विष्टि', 'शकुनि', 'चतुष्पद', 'नाग', 'किंस्तुघ्न']
  };
  Yoga = {
    name_en_NP: [
      'Vishkambha',
      'Prithi',
      'Ayushman',
      'Saubhagya',
      'Sobhana',
      'Atiganda',
      'Sukarman',
      'Dhrithi',
      'Soola',
      'Ganda',
      'Vridhi',
      'Dhruva',
      'Vyaghata',
      'Harshana',
      'Vajra',
      'Siddhi',
      'Vyatipata',
      'Variyan',
      'Parigha',
      'Siva',
      'Siddha',
      'Sadhya',
      'Subha',
      'Sukla',
      'Bramha',
      'Indra',
      'Vaidhruthi',
    ],
    name: [ 'विष्कम्भ', 'पृथी', 'आयुष्मान', 'सौभाग्य', 'शोभन', 'अतिगण्ड', 'सुकर्मा', 'धृति', 'शूल', 'गण्ड', 'वृद्धि', 'ध्रुव', 'व्याघात', 'हर्षण', 'वज्र', 'असृक्', 'व्यतिपात', 'वरीयान', 'परिघ', 'शिव', 'सिद्ध', 'साध्ध', 'शुभ', 'शुक्ल', 'ब्रह्म', 'इन्द्र', 'वैधृति'],
  };
}
